language: java

jdk:
  - openjdk17

before_install:
  - chmod +x gradlew

install: true

deploy:
  provider: s3
  access_key_id: $acces_key
  secret_access_key: $secret_acces_key
  local_dir: build/libs
  bucket: "pruebatravisci"
  skip_cleanup: true

script:
  - ./gradlew build